/* @pjs pauseOnBlur="true";
        font="data/diediedie.regular.ttf";
        preload="data/background.jpg,
                 data/bronze.jpg,
                 data/golden.jpg,
                 data/lose.jpg,
                 data/pause.jpg,
                 data/silver.jpg",
                 data/start.jpg,
                 data/pic/battle.png,
                 data/pic/bird.png,
                 data/pic/KID1.png,
                 data/pic/KID2.png,
                 data/pic/kids1.png,
                 data/pic/kids2.png,
                 data/pic/kids3.png,
                 data/pic/magic.png,
                 data/pic/People1.png,
                 data/pic/People2.png,
                 data/pic/pumpkin.png,
                 data/pic/spider.png,
                 data/pic/Witch.png;
                 */
