/* @pjs pauseOnBlur="true"; 
        preload= "data/background.png,
                  data/boy mouthopen.png,
                  data/boy.png,
                  data/boycry.png,
                  data/ccake.png,
                  data/donet.png,
                  data/END.png,
                  data/example 2.jpg,
                  data/ggirl.png,
                  data/ggirlcry.png,
                  data/ggirlopen.png,
                  data/heart.png,
                  data/house.png,
                  data/pink candy.png,
                  data/rgirl.png,
                  data/rgirlcry.png,
                  data/rgirlopen.png,
                  data/scake.png,
                  data/START.png,
                  data/yellow candy.png";
                  */
